### ISSUE TITLE
Emails don't seem to roundtrip

### ISSUE THREAD

**Issue by NorfairKing** [purebred-mua/purebred-email#67] opened 2021-10-12 22:47 UTC
I don't know if the RFC's fault, or the implementation, but it looks like parsing and rendering messages doesn't roundtrip.

![roundtrip](https://user-images.githubusercontent.com/3521180/137039053-98ed5f4b-c05d-42ab-8458-621c8a5a9a55.png)

Is this intentional?

**Comment by NorfairKing** [comment] 2021-10-13 10:13
It would also be nice if roundtrip tests like this were part of the test suite.
Now I have to write tests to find bugs in the library rather than in my own.
I'd be happy to help with writing tests if you like.

**Comment by NorfairKing** [comment] 2021-10-14 11:26
> The failure you encountered does not arise in my tests because the generator uses the "proper" APIs for building multipart messages, and these added the required headers.

AHA! We may want to add some comments about that. Not every value is valid (that's what `validity` is for).



> IMF and MIME are complex. Although I believe it is possible to define data structures that can only represent conformant messages, and which round trip perfectly, the complexity would be enormous. I would prefer to focus on ergonomic interfaces for common use cases than go down that very deep rabbit hole.

Yes I think that's entirely right. Thanks for pointing this out and not jumping down that rabit hole for me!

> @NorfairKing Of course, if you want to help develop purebred-email, your contributions are most welcome! But perhaps we can start with a question: what is your use case, and what are the gaps and pain points in purebred-email for your use case?

I'm considering building a haskell email client here: https://github.com/NorfairKing/kalm
Nothing works yet, but I've made a diagram: 
![diagram](https://user-images.githubusercontent.com/3521180/137308731-36f128e2-98ef-4d21-a8e5-5886104d86a9.png)

**Comment by frasertweedale** [comment] 2021-10-14 13:49
@NorfairKing are you aware of https://github.com/purebred-mua/purebred?  It's a terminal MUA using notmuch for mail storage, and sits in pretty much the same box as Kalm in that diagram above.  We wrote *purebred-email* for working with the message data.

I don't wish to deter you from doing your own thing - but if the goals are similar and you like purebred's approach (*mutt*-esque UX) it could be good to work together.

For sure, I can add comments about validity (I think I already did in the unreleased code on master, but could probably say more).  I will consider `Validity` type class, and thank you for bringing it to my attention.

**Comment by frasertweedale** [comment] 2021-10-14 23:23
@NorfairKing all good.  At the end of the day if we can't agree, we can do different things.  But it is good if we can find common ground and work from there.  It might be better to discuss each of the topics in more detail in issues filed against purebred, but here are some brief thoughts:

## stack build

I have no interest personally, but no fundamental objection.  We used to have it at the beginning, but it made testing very difficult due to "the xmonad way" of configuration - that is, recompilation (see https://hackage.haskell.org/package/dyre for details).  So we removed it.  If you want to own it (with or without tests), you can have it.  Just keep in mind we are sometimes using versions of libraries that are not in Stackage or LTS releases.

## sending

It's a general interface, you could implement an SMTP sender today.  OOTB we ship an implementation that invokes a local mailer.  We use a different implementation in the test suite to put "sent" mail aside for inspection.

An SMTP mailer should be provided as a separate "add-on" library, not part of core purebred (to avoid the dependencies).

## receiving

Could you describe in more detail your requirements?  With purebred, mail is stored on the filesystem and indexed using *notmuch*.  We designed purebred with an assumption that an external MDA (e.g. fetchmail + maildrop) will take care of retrieval/delivery.  The problem is well solved and we didn't see any reason to solve it again using Haskell.  That said, I do see some possible advantages of integrating mail retrieval/delivery with purebred:

1. fewer components for users to configure (at the expense of more stuff to configure in purebred itself)
2. better "new mail" notification UX
3. better ways to pre-process mail, e.g. for automatic tagging, with access to the full power of Haskell and purebred-email for analysing received messages

If you really need it, we will design and develop the interfaces to solve it, and the implementation(s) can be shipped as add-on libraries.

## abstractions and optics

Difference of opinion ;)

**Comment by frasertweedale** [comment] 2021-11-23 02:53
I'm closing this now that v0.5 was released, which contained some of the type improvements discussed above.

**Closed by frasertweedale** 2021-11-23 02:53 UTC
